//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Receta
    {
        public int id_detalle { get; set; }
        public Nullable<int> id_receta { get; set; }
        public Nullable<int> id_medicamento { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual Medicamentos Medicamentos { get; set; }
        public virtual Recetas Recetas { get; set; }
    }
}
