//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historia_Clinica
    {
        public int id_historia { get; set; }
        public Nullable<int> id_paciente { get; set; }
        public Nullable<int> id_medico { get; set; }
        public Nullable<System.DateTime> fecha_consulta { get; set; }
        public string sintomas { get; set; }
        public string diagnostico { get; set; }
        public string tratamiento { get; set; }
        public string observaciones { get; set; }
    
        public virtual Medicos Medicos { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
